# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.fetch:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    docker-image: {in-tree: base}

jobs:
    win-dev-env:
        description: Windows Dev-Enviroment
        fetch:
            type: static-url
            url: https://s3.nl-ams.scw.cloud/basti.data/vsstudio.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=SCW71D8GJXY19DG32Q1Y%2F20220202%2Fnl-ams%2Fs3%2Faws4_request&X-Amz-Date=20220202T182650Z&X-Amz-Expires=521996&X-Amz-Signature=32a384e55fa3a980dee6bbc00d3a6f382dcd44f9c3c58b890e0f436bce77d8c9&X-Amz-SignedHeaders=host
            artifact-name: vsstudio.zip
            sha256: A64814151AD67153F796AA0B7987B82F3E1AD98076F04B59740A597B62A7FB80
            size: 1117343875
        #artifact-prefix: vpn/win-dev-env
        fetch-alias: win-dev-env
    win-perl:
        description: Strawberry Perl
        fetch:
            type: static-url
            url: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.zip
            artifact-name: strawberry-perl.zip
            sha256: AEB973DA474F14210D3E1A1F942DCF779E2AE7E71E4C535E6C53EBABE632CC98
            size: 158837368
        #artifact-prefix: vpn/win-perl
        fetch-alias: win-perl
    qt-6.2.3:
        description: QT souce 
        fetch:
            type: static-url
            url: https://download.qt.io/archive/qt/6.2/6.2.3/single/qt-everywhere-src-6.2.3.zip
            artifact-name: qt_src.zip
            sha256: DD68B5FD5812E3DD25BF9ED67F3051835503192C168CDC8D86ADDC08848D7BDA
            size: 1101112955
        fetch-alias: qt-6.2.3-source


    